# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(887, 499)
        Dialog.setAcceptDrops(False)
        Dialog.setAutoFillBackground(False)
        self.time_available_grpbox = QtWidgets.QGroupBox(Dialog)
        self.time_available_grpbox.setGeometry(QtCore.QRect(30, 20, 341, 51))
        self.time_available_grpbox.setObjectName("time_available_grpbox")
        self.time_layout_horiz = QtWidgets.QHBoxLayout(self.time_available_grpbox)
        self.time_layout_horiz.setContentsMargins(11, 11, 11, 11)
        self.time_layout_horiz.setSpacing(6)
        self.time_layout_horiz.setObjectName("time_layout_horiz")
        self.time_available_lbl = QtWidgets.QLabel(self.time_available_grpbox)
        self.time_available_lbl.setObjectName("time_available_lbl")
        self.time_layout_horiz.addWidget(self.time_available_lbl)
        self.available_from_time_edit = QtWidgets.QTimeEdit(self.time_available_grpbox)
        self.available_from_time_edit.setObjectName("available_from_time_edit")
        self.time_layout_horiz.addWidget(self.available_from_time_edit)
        self.time_to_lbl = QtWidgets.QLabel(self.time_available_grpbox)
        self.time_to_lbl.setObjectName("time_to_lbl")
        self.time_layout_horiz.addWidget(self.time_to_lbl)
        self.available_to_time_edit = QtWidgets.QTimeEdit(self.time_available_grpbox)
        self.available_to_time_edit.setObjectName("available_to_time_edit")
        self.time_layout_horiz.addWidget(self.available_to_time_edit)
        self.location_grpbox = QtWidgets.QGroupBox(Dialog)
        self.location_grpbox.setGeometry(QtCore.QRect(30, 120, 251, 51))
        self.location_grpbox.setObjectName("location_grpbox")
        self.location_layout_horiz = QtWidgets.QHBoxLayout(self.location_grpbox)
        self.location_layout_horiz.setContentsMargins(11, 11, 11, 11)
        self.location_layout_horiz.setSpacing(6)
        self.location_layout_horiz.setObjectName("location_layout_horiz")
        self.location_lbl = QtWidgets.QLabel(self.location_grpbox)
        self.location_lbl.setObjectName("location_lbl")
        self.location_layout_horiz.addWidget(self.location_lbl)
        self.location_comb = QtWidgets.QComboBox(self.location_grpbox)
        self.location_comb.setObjectName("location_comb")
        self.location_comb.addItem("")
        self.location_comb.addItem("")
        self.location_layout_horiz.addWidget(self.location_comb)
        self.days_available_grpbox = QtWidgets.QGroupBox(Dialog)
        self.days_available_grpbox.setGeometry(QtCore.QRect(30, 170, 611, 41))
        self.days_available_grpbox.setObjectName("days_available_grpbox")
        self.location_layout_horiz_2 = QtWidgets.QHBoxLayout(self.days_available_grpbox)
        self.location_layout_horiz_2.setContentsMargins(11, 11, 11, 11)
        self.location_layout_horiz_2.setSpacing(6)
        self.location_layout_horiz_2.setObjectName("location_layout_horiz_2")
        self.days_available_lbl = QtWidgets.QLabel(self.days_available_grpbox)
        self.days_available_lbl.setObjectName("days_available_lbl")
        self.location_layout_horiz_2.addWidget(self.days_available_lbl)
        self.all_days_chk = QtWidgets.QCheckBox(self.days_available_grpbox)
        self.all_days_chk.setObjectName("all_days_chk")
        self.location_layout_horiz_2.addWidget(self.all_days_chk)
        self.monday_chk = QtWidgets.QCheckBox(self.days_available_grpbox)
        self.monday_chk.setObjectName("monday_chk")
        self.location_layout_horiz_2.addWidget(self.monday_chk)
        self.tues_chk = QtWidgets.QCheckBox(self.days_available_grpbox)
        self.tues_chk.setObjectName("tues_chk")
        self.location_layout_horiz_2.addWidget(self.tues_chk)
        self.wed_chk = QtWidgets.QCheckBox(self.days_available_grpbox)
        self.wed_chk.setObjectName("wed_chk")
        self.location_layout_horiz_2.addWidget(self.wed_chk)
        self.thurs_chk = QtWidgets.QCheckBox(self.days_available_grpbox)
        self.thurs_chk.setObjectName("thurs_chk")
        self.location_layout_horiz_2.addWidget(self.thurs_chk)
        self.fri_chk = QtWidgets.QCheckBox(self.days_available_grpbox)
        self.fri_chk.setObjectName("fri_chk")
        self.location_layout_horiz_2.addWidget(self.fri_chk)
        self.category_grpbox = QtWidgets.QGroupBox(Dialog)
        self.category_grpbox.setGeometry(QtCore.QRect(30, 70, 261, 51))
        self.category_grpbox.setObjectName("category_grpbox")
        self.category_layout_horiz = QtWidgets.QHBoxLayout(self.category_grpbox)
        self.category_layout_horiz.setContentsMargins(11, 11, 11, 11)
        self.category_layout_horiz.setSpacing(6)
        self.category_layout_horiz.setObjectName("category_layout_horiz")
        self.categories_lbl = QtWidgets.QLabel(self.category_grpbox)
        self.categories_lbl.setObjectName("categories_lbl")
        self.category_layout_horiz.addWidget(self.categories_lbl)
        self.category_comb = QtWidgets.QComboBox(self.category_grpbox)
        self.category_comb.setObjectName("category_comb")
        self.category_comb.addItem("")
        self.category_comb.addItem("")
        self.category_comb.addItem("")
        self.category_layout_horiz.addWidget(self.category_comb)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(630, 470, 241, 32))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.professor_grpbox = QtWidgets.QGroupBox(Dialog)
        self.professor_grpbox.setGeometry(QtCore.QRect(30, 210, 251, 51))
        self.professor_grpbox.setObjectName("professor_grpbox")
        self.professor_layout_horiz = QtWidgets.QHBoxLayout(self.professor_grpbox)
        self.professor_layout_horiz.setContentsMargins(11, 11, 11, 11)
        self.professor_layout_horiz.setSpacing(6)
        self.professor_layout_horiz.setObjectName("professor_layout_horiz")
        self.professor_lbl = QtWidgets.QLabel(self.professor_grpbox)
        self.professor_lbl.setObjectName("professor_lbl")
        self.professor_layout_horiz.addWidget(self.professor_lbl)
        self.professor_comb = QtWidgets.QComboBox(self.professor_grpbox)
        self.professor_comb.setObjectName("professor_comb")
        self.professor_comb.addItem("")
        self.professor_comb.addItem("")
        self.professor_layout_horiz.addWidget(self.professor_comb)
        self.min_courses_grpbox = QtWidgets.QGroupBox(Dialog)
        self.min_courses_grpbox.setGeometry(QtCore.QRect(30, 260, 301, 51))
        self.min_courses_grpbox.setObjectName("min_courses_grpbox")
        self.professor_layout_horiz_2 = QtWidgets.QHBoxLayout(self.min_courses_grpbox)
        self.professor_layout_horiz_2.setContentsMargins(11, 11, 11, 11)
        self.professor_layout_horiz_2.setSpacing(6)
        self.professor_layout_horiz_2.setObjectName("professor_layout_horiz_2")
        self.min_courses_lbl = QtWidgets.QLabel(self.min_courses_grpbox)
        self.min_courses_lbl.setObjectName("min_courses_lbl")
        self.professor_layout_horiz_2.addWidget(self.min_courses_lbl)
        self.min_courses_spin = QtWidgets.QSpinBox(self.min_courses_grpbox)
        self.min_courses_spin.setObjectName("min_courses_spin")
        self.professor_layout_horiz_2.addWidget(self.min_courses_spin)
        self.max_courses_grpbox = QtWidgets.QGroupBox(Dialog)
        self.max_courses_grpbox.setGeometry(QtCore.QRect(30, 310, 301, 51))
        self.max_courses_grpbox.setObjectName("max_courses_grpbox")
        self.professor_layout_horiz_3 = QtWidgets.QHBoxLayout(self.max_courses_grpbox)
        self.professor_layout_horiz_3.setContentsMargins(11, 11, 11, 11)
        self.professor_layout_horiz_3.setSpacing(6)
        self.professor_layout_horiz_3.setObjectName("professor_layout_horiz_3")
        self.professor_lbl_3 = QtWidgets.QLabel(self.max_courses_grpbox)
        self.professor_lbl_3.setObjectName("professor_lbl_3")
        self.professor_layout_horiz_3.addWidget(self.professor_lbl_3)
        self.max_courses_spin = QtWidgets.QSpinBox(self.max_courses_grpbox)
        self.max_courses_spin.setObjectName("max_courses_spin")
        self.professor_layout_horiz_3.addWidget(self.max_courses_spin)
        self.subject_grpbox = QtWidgets.QGroupBox(Dialog)
        self.subject_grpbox.setGeometry(QtCore.QRect(30, 360, 341, 51))
        self.subject_grpbox.setObjectName("subject_grpbox")
        self.location_layout_horiz_3 = QtWidgets.QHBoxLayout(self.subject_grpbox)
        self.location_layout_horiz_3.setContentsMargins(11, 11, 11, 11)
        self.location_layout_horiz_3.setSpacing(6)
        self.location_layout_horiz_3.setObjectName("location_layout_horiz_3")
        self.subject_lbl = QtWidgets.QLabel(self.subject_grpbox)
        self.subject_lbl.setObjectName("subject_lbl")
        self.location_layout_horiz_3.addWidget(self.subject_lbl)
        self.subject_comb = QtWidgets.QComboBox(self.subject_grpbox)
        self.subject_comb.setObjectName("subject_comb")
        self.subject_comb.addItem("")
        self.subject_comb.addItem("")
        self.subject_comb.addItem("")
        self.location_layout_horiz_3.addWidget(self.subject_comb)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Preferences"))
        self.time_available_lbl.setText(_translate("Dialog", "Time Available:"))
        self.time_to_lbl.setText(_translate("Dialog", "to"))
        self.location_lbl.setText(_translate("Dialog", "Location:"))
        self.location_comb.setItemText(0, _translate("Dialog", "Sullivan"))
        self.location_comb.setItemText(1, _translate("Dialog", "Petty"))
        self.days_available_lbl.setText(_translate("Dialog", "Days Available:"))
        self.all_days_chk.setText(_translate("Dialog", "All Days"))
        self.monday_chk.setText(_translate("Dialog", "Monday"))
        self.tues_chk.setText(_translate("Dialog", "Tuesday"))
        self.wed_chk.setText(_translate("Dialog", "Wednesday"))
        self.thurs_chk.setText(_translate("Dialog", "Thursday"))
        self.fri_chk.setText(_translate("Dialog", "Friday"))
        self.categories_lbl.setText(_translate("Dialog", "Categories and Attributes:"))
        self.category_comb.setItemText(0, _translate("Dialog", "WI"))
        self.category_comb.setItemText(1, _translate("Dialog", "GLT"))
        self.category_comb.setItemText(2, _translate("Dialog", "SI"))
        self.professor_lbl.setText(_translate("Dialog", "Professor:"))
        self.professor_comb.setItemText(0, _translate("Dialog", "Dr. Howie"))
        self.professor_comb.setItemText(1, _translate("Dialog", "Dr. Aleshire"))
        self.min_courses_lbl.setText(_translate("Dialog", "Minimum Number of Courses:"))
        self.professor_lbl_3.setText(_translate("Dialog", "Maximum Number of Courses:"))
        self.subject_lbl.setText(_translate("Dialog", "Subject:"))
        self.subject_comb.setItemText(0, _translate("Dialog", "Computer Science"))
        self.subject_comb.setItemText(1, _translate("Dialog", "Mathematics"))
        self.subject_comb.setItemText(2, _translate("Dialog", "Statistics"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

